CONFIG_NAME: '3stages'
DATASET_NAME: 'car'
DATA_DIR: '../../data/cars'
# DATASET_NAME: 'cub'
# DATA_DIR: '../../data/birds'
SAVE_DIR: '../output/vis'
GPU_ID: '1'
WORKERS: 4

SUPER_CATEGORIES: 20   # For CUB
FINE_GRAINED_CATEGORIES: 196  # For CUB
BG_CATEGORIES: 30
# FINE_GRAINED_CATEGORIES: 200  # For CUB
# BG_CATEGORIES: 200
# NUM_B_PER_P: 10  # b/p
# NUM_P_PER_B: 2   # p/b
# NUM_C_PER_B: 1   # c/b

TIED_CODES: True   # Do NOT change this to False during training.

TRAIN:
    FLAG: True
    NET_G: ''
    NET_D: ''
    MATCHER: ''
    # NET_G: '../output/car_2021_01_02_23_51_16/Model/netG_10000_depth2.pth'
    # NET_D: '../output/car_2021_01_02_23_51_16/Model/netD'
    # MATCHER: '../output/car_2021_01_02_23_51_16/Model/matcher_depth2.pth'

    MAX_EPOCH: 600
    HARDNEG_MAX_ITER: 1500
    SNAPSHOT_INTERVAL: 500
    SAVEMODEL_INTERVAL: 10000
    SNAPSHOT_INTERVAL_HARDNEG: 500
    DISCRIMINATOR_LR: 0.0002
    GENERATOR_LR: 0.0002
    MIN_FG_CVG: 0.3
    # MIN_BG_CVG: 0.1

    START_DEPTH: 2 # 32 has depth 0; should match loaded model depth
    END_DEPTH: 2  # 256 has depth 3
    BATCHSIZE_PER_DEPTH: [64, 8, 24, 8]
    BLEND_EPOCHS_PER_DEPTH: [0, 0, 0, 80]
    STABLE_EPOCHS_PER_DEPTH: [60, 100, 160, 220]

GAN:
    DF_DIM: 64
    GF_DIM: 64
    Z_DIM: 100
    R_NUM: 2
