CONFIG_NAME: '3stages'
DATASET_NAME: 'car'
DATA_DIR: '../../data/cars'
# DATASET_NAME: 'cub'
# DATA_DIR: '../../data/birds'
SAVE_DIR: '../output/vis'
GPU_ID: '1'
WORKERS: 4

BG_CATEGORIES: 120
FG_CATEGORIES: 60
# FINE_GRAINED_CATEGORIES: 196
# FINE_GRAINED_CATEGORIES: 200  # For CUB
# BG_CATEGORIES: 200
# NUM_B_PER_P: 10  # b/p
# NUM_P_PER_B: 2   # p/b
# NUM_C_PER_B: 1   # c/b

TIED_CODES: True   # Do NOT change this to False during training.

TRAIN:
    FLAG: True
    NET_G: ''  # Specify the generator path to resume training
    NET_D: ''  # Specify the discriminator path to resume training
    MAX_EPOCH: 600
    HARDNEG_MAX_ITER: 1500
    SNAPSHOT_INTERVAL: 1000
    SAVEMODEL_INTERVAL: 20000
    SNAPSHOT_INTERVAL_HARDNEG: 500
    DISCRIMINATOR_LR: 0.00015
    GENERATOR_LR: 0.0002
    BIDISCRIMINATOR_LR: 0.0002
    MKPRED_LR: 0.0002
    MIN_FG_CVG: 0.2
    MIN_BG_CVG: 0.2

    START_DEPTH: 2 # 32 has depth 0; should match loaded model depth
    END_DEPTH: 2  # 256 has depth 3
    BATCHSIZE_PER_DEPTH: [64, 8, 32, 8]
    BLEND_EPOCHS_PER_DEPTH: [0, 0, 0, 80]
    STABLE_EPOCHS_PER_DEPTH: [60, 100, 200, 220]

GAN:
    DF_DIM: 64
    GF_DIM: 64
    Z_DIM: 100
    R_NUM: 2
