CONFIG_NAME: '3stages'
DATASET_NAME: 'CUB'
DATA_DIR: '../../data/birds'
SAVE_DIR: '../output/vis'
GPU_ID: '1'
WORKERS: 4

SUPER_CATEGORIES: 20   # For CUB
FINE_GRAINED_CATEGORIES: 200  # For CUB
TIED_CODES: True   # Do NOT change this to False during training.

TRAIN:
    FLAG: True
    NET_G: ''  # Specify the generator path to resume training
    NET_D: ''  # Specify the discriminator path to resume training
    MAX_EPOCH: 600
    HARDNEG_MAX_ITER: 1500
    SNAPSHOT_INTERVAL: 1000
    SAVEMODEL_INTERVAL: 50000
    SNAPSHOT_INTERVAL_HARDNEG: 500
    DISCRIMINATOR_LR: 0.0002
    GENERATOR_LR: 0.0002
    BG_CONN_WT: 100.
    FG_CONN_WT: 100.
    RECON_WT: 1.

    PAD: [30, 26, 21, 10]
    START_DEPTH: 1 # 32 has depth 0; should match loaded model depth
    END_DEPTH: 1  # 256 has depth 3
    BATCHSIZE_PER_DEPTH: [64, 6, 16, 8]
    BLEND_EPOCHS_PER_DEPTH: [0, 0, 60, 80]
    STABLE_EPOCHS_PER_DEPTH: [60, 100, 160, 220]

GAN:
    DF_DIM: 64
    GF_DIM: 64
    Z_DIM: 100
    R_NUM: 2
